# Generated by Django 3.2.16 on 2022-12-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rents',
            name='title',
            field=models.CharField(default=None, max_length=120),
        ),
        migrations.AlterField(
            model_name='rents',
            name='date_rented',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='rents',
            name='last_payment_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='rents',
            name='price',
            field=models.FloatField(default=None),
        ),
    ]
