# Generated by Django 3.2.16 on 2022-12-19 10:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0002_auto_20221219_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rents',
            name='last_payment_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
