# Generated by Django 3.2.16 on 2022-12-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='')),
                ('address', models.TextField(max_length=250)),
                ('option', models.TextField(choices=[('SELL', 'SELL'), ('BUY', 'BUY'), ('TAKE RENT', 'TAKE RENT'), ('GIVE RENT', 'GIVE RENT')], default='TAKE RENT', max_length=9)),
                ('price', models.DecimalField(decimal_places=3, max_digits=8)),
            ],
        ),
    ]
