# Generated by Django 3.2.16 on 2022-12-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='balcony',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='house',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='kitchen',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='house',
            name='rooms',
            field=models.IntegerField(default=1),
        ),
    ]
