# Generated by Django 4.0.4 on 2022-12-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_auto_20221214_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='washroom',
            field=models.IntegerField(default=1),
        ),
    ]
