# Generated by Django 3.2.16 on 2022-12-14 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_house_washroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='image',
        ),
    ]
