# Generated by Django 3.2.16 on 2022-12-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_remove_house_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='inventory'),
        ),
    ]
