# Generated by Django 3.2.16 on 2022-12-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0005_house_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='option',
            field=models.TextField(choices=[('TAKE RENT', 'TAKE RENT'), ('GIVE RENT', 'GIVE RENT')], default='TAKE RENT', max_length=9),
        ),
    ]
