# Generated by Django 3.2.16 on 2022-12-17 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0006_alter_house_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='owner',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
