# Generated by Django 3.2.16 on 2022-12-17 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('house', '0007_house_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='option',
        ),
        migrations.RemoveField(
            model_name='house',
            name='owner',
        ),
        migrations.AddField(
            model_name='house',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
